/**
 * 古诗词数据库 - 小学1-6年级必背古诗词
 */

export interface Poem {
  id: string;
  title: string;
  author: string;
  dynasty: string;
  content: string[]; // 每行一句
  grade: number;     // 1-6
}

export const poems: Poem[] = [
  // ===== 一年级 =====
  {
    id: 'g1-01',
    title: '咏鹅',
    author: '骆宾王',
    dynasty: '唐',
    content: ['鹅，鹅，鹅，', '曲项向天歌。', '白毛浮绿水，', '红掌拨清波。'],
    grade: 1,
  },
  {
    id: 'g1-02',
    title: '江南',
    author: '汉乐府',
    dynasty: '汉',
    content: ['江南可采莲，', '莲叶何田田。', '鱼戏莲叶间。', '鱼戏莲叶东，', '鱼戏莲叶西，', '鱼戏莲叶南，', '鱼戏莲叶北。'],
    grade: 1,
  },
  {
    id: 'g1-03',
    title: '画',
    author: '王维',
    dynasty: '唐',
    content: ['远看山有色，', '近听水无声。', '春去花还在，', '人来鸟不惊。'],
    grade: 1,
  },
  {
    id: 'g1-04',
    title: '悯农（其二）',
    author: '李绅',
    dynasty: '唐',
    content: ['锄禾日当午，', '汗滴禾下土。', '谁知盘中餐，', '粒粒皆辛苦。'],
    grade: 1,
  },
  {
    id: 'g1-05',
    title: '古朗月行',
    author: '李白',
    dynasty: '唐',
    content: ['小时不识月，', '呼作白玉盘。', '又疑瑶台镜，', '飞在青云端。'],
    grade: 1,
  },
  {
    id: 'g1-06',
    title: '风',
    author: '李峤',
    dynasty: '唐',
    content: ['解落三秋叶，', '能开二月花。', '过江千尺浪，', '入竹万竿斜。'],
    grade: 1,
  },
  {
    id: 'g1-07',
    title: '春晓',
    author: '孟浩然',
    dynasty: '唐',
    content: ['春眠不觉晓，', '处处闻啼鸟。', '夜来风雨声，', '花落知多少。'],
    grade: 1,
  },
  {
    id: 'g1-08',
    title: '静夜思',
    author: '李白',
    dynasty: '唐',
    content: ['床前明月光，', '疑是地上霜。', '举头望明月，', '低头思故乡。'],
    grade: 1,
  },
  {
    id: 'g1-09',
    title: '赠汪伦',
    author: '李白',
    dynasty: '唐',
    content: ['李白乘舟将欲行，', '忽闻岸上踏歌声。', '桃花潭水深千尺，', '不及汪伦送我情。'],
    grade: 1,
  },
  {
    id: 'g1-10',
    title: '寻隐者不遇',
    author: '贾岛',
    dynasty: '唐',
    content: ['松下问童子，', '言师采药去。', '只在此山中，', '云深不知处。'],
    grade: 1,
  },

  // ===== 二年级 =====
  {
    id: 'g2-01',
    title: '村居',
    author: '高鼎',
    dynasty: '清',
    content: ['草长莺飞二月天，', '拂堤杨柳醉春烟。', '儿童散学归来早，', '忙趁东风放纸鸢。'],
    grade: 2,
  },
  {
    id: 'g2-02',
    title: '咏柳',
    author: '贺知章',
    dynasty: '唐',
    content: ['碧玉妆成一树高，', '万条垂下绿丝绦。', '不知细叶谁裁出，', '二月春风似剪刀。'],
    grade: 2,
  },
  {
    id: 'g2-03',
    title: '赋得古原草送别',
    author: '白居易',
    dynasty: '唐',
    content: ['离离原上草，', '一岁一枯荣。', '野火烧不尽，', '春风吹又生。'],
    grade: 2,
  },
  {
    id: 'g2-04',
    title: '望庐山瀑布',
    author: '李白',
    dynasty: '唐',
    content: ['日照香炉生紫烟，', '遥看瀑布挂前川。', '飞流直下三千尺，', '疑是银河落九天。'],
    grade: 2,
  },
  {
    id: 'g2-05',
    title: '绝句',
    author: '杜甫',
    dynasty: '唐',
    content: ['两个黄鹂鸣翠柳，', '一行白鹭上青天。', '窗含西岭千秋雪，', '门泊东吴万里船。'],
    grade: 2,
  },
  {
    id: 'g2-06',
    title: '小池',
    author: '杨万里',
    dynasty: '宋',
    content: ['泉眼无声惜细流，', '树阴照水爱晴柔。', '小荷才露尖尖角，', '早有蜻蜓立上头。'],
    grade: 2,
  },
  {
    id: 'g2-07',
    title: '登鹳雀楼',
    author: '王之涣',
    dynasty: '唐',
    content: ['白日依山尽，', '黄河入海流。', '欲穷千里目，', '更上一层楼。'],
    grade: 2,
  },
  {
    id: 'g2-08',
    title: '望天门山',
    author: '李白',
    dynasty: '唐',
    content: ['天门中断楚江开，', '碧水东流至此回。', '两岸青山相对出，', '孤帆一片日边来。'],
    grade: 2,
  },
  {
    id: 'g2-09',
    title: '夜宿山寺',
    author: '李白',
    dynasty: '唐',
    content: ['危楼高百尺，', '手可摘星辰。', '不敢高声语，', '恐惊天上人。'],
    grade: 2,
  },
  {
    id: 'g2-10',
    title: '敕勒歌',
    author: '北朝民歌',
    dynasty: '北朝',
    content: ['敕勒川，阴山下，', '天似穹庐，笼盖四野。', '天苍苍，野茫茫，', '风吹草低见牛羊。'],
    grade: 2,
  },

  // ===== 三年级 =====
  {
    id: 'g3-01',
    title: '山行',
    author: '杜牧',
    dynasty: '唐',
    content: ['远上寒山石径斜，', '白云生处有人家。', '停车坐爱枫林晚，', '霜叶红于二月花。'],
    grade: 3,
  },
  {
    id: 'g3-02',
    title: '赠刘景文',
    author: '苏轼',
    dynasty: '宋',
    content: ['荷尽已无擎雨盖，', '菊残犹有傲霜枝。', '一年好景君须记，', '最是橙黄橘绿时。'],
    grade: 3,
  },
  {
    id: 'g3-03',
    title: '夜书所见',
    author: '叶绍翁',
    dynasty: '宋',
    content: ['萧萧梧叶送寒声，', '江上秋风动客情。', '知有儿童挑促织，', '夜深篱落一灯明。'],
    grade: 3,
  },
  {
    id: 'g3-04',
    title: '望洞庭',
    author: '刘禹锡',
    dynasty: '唐',
    content: ['湖光秋月两相和，', '潭面无风镜未磨。', '遥望洞庭山水翠，', '白银盘里一青螺。'],
    grade: 3,
  },
  {
    id: 'g3-05',
    title: '饮湖上初晴后雨',
    author: '苏轼',
    dynasty: '宋',
    content: ['水光潋滟晴方好，', '山色空蒙雨亦奇。', '欲把西湖比西子，', '淡妆浓抹总相宜。'],
    grade: 3,
  },
  {
    id: 'g3-06',
    title: '九月九日忆山东兄弟',
    author: '王维',
    dynasty: '唐',
    content: ['独在异乡为异客，', '每逢佳节倍思亲。', '遥知兄弟登高处，', '遍插茱萸少一人。'],
    grade: 3,
  },
  {
    id: 'g3-07',
    title: '清明',
    author: '杜牧',
    dynasty: '唐',
    content: ['清明时节雨纷纷，', '路上行人欲断魂。', '借问酒家何处有？', '牧童遥指杏花村。'],
    grade: 3,
  },
  {
    id: 'g3-08',
    title: '早发白帝城',
    author: '李白',
    dynasty: '唐',
    content: ['朝辞白帝彩云间，', '千里江陵一日还。', '两岸猿声啼不住，', '轻舟已过万重山。'],
    grade: 3,
  },
  {
    id: 'g3-09',
    title: '绝句',
    author: '杜甫',
    dynasty: '唐',
    content: ['迟日江山丽，', '春风花草香。', '泥融飞燕子，', '沙暖睡鸳鸯。'],
    grade: 3,
  },
  {
    id: 'g3-10',
    title: '滁州西涧',
    author: '韦应物',
    dynasty: '唐',
    content: ['独怜幽草涧边生，', '上有黄鹂深树鸣。', '春潮带雨晚来急，', '野渡无人舟自横。'],
    grade: 3,
  },

  // ===== 四年级 =====
  {
    id: 'g4-01',
    title: '题西林壁',
    author: '苏轼',
    dynasty: '宋',
    content: ['横看成岭侧成峰，', '远近高低各不同。', '不识庐山真面目，', '只缘身在此山中。'],
    grade: 4,
  },
  {
    id: 'g4-02',
    title: '游山西村',
    author: '陆游',
    dynasty: '宋',
    content: ['莫笑农家腊酒浑，', '丰年留客足鸡豚。', '山重水复疑无路，', '柳暗花明又一村。'],
    grade: 4,
  },
  {
    id: 'g4-03',
    title: '黄鹤楼送孟浩然之广陵',
    author: '李白',
    dynasty: '唐',
    content: ['故人西辞黄鹤楼，', '烟花三月下扬州。', '孤帆远影碧空尽，', '唯见长江天际流。'],
    grade: 4,
  },
  {
    id: 'g4-04',
    title: '送元二使安西',
    author: '王维',
    dynasty: '唐',
    content: ['渭城朝雨浥轻尘，', '客舍青青柳色新。', '劝君更尽一杯酒，', '西出阳关无故人。'],
    grade: 4,
  },
  {
    id: 'g4-05',
    title: '暮江吟',
    author: '白居易',
    dynasty: '唐',
    content: ['一道残阳铺水中，', '半江瑟瑟半江红。', '可怜九月初三夜，', '露似真珠月似弓。'],
    grade: 4,
  },
  {
    id: 'g4-06',
    title: '题临安邸',
    author: '林升',
    dynasty: '宋',
    content: ['山外青山楼外楼，', '西湖歌舞几时休？', '暖风熏得游人醉，', '直把杭州作汴州。'],
    grade: 4,
  },
  {
    id: 'g4-07',
    title: '出塞',
    author: '王昌龄',
    dynasty: '唐',
    content: ['秦时明月汉时关，', '万里长征人未还。', '但使龙城飞将在，', '不教胡马度阴山。'],
    grade: 4,
  },
  {
    id: 'g4-08',
    title: '凉州词',
    author: '王翰',
    dynasty: '唐',
    content: ['葡萄美酒夜光杯，', '欲饮琵琶马上催。', '醉卧沙场君莫笑，', '古来征战几人回？'],
    grade: 4,
  },
  {
    id: 'g4-09',
    title: '夏日绝句',
    author: '李清照',
    dynasty: '宋',
    content: ['生当作人杰，', '死亦为鬼雄。', '至今思项羽，', '不肯过江东。'],
    grade: 4,
  },
  {
    id: 'g4-10',
    title: '蜂',
    author: '罗隐',
    dynasty: '唐',
    content: ['不论平地与山尖，', '无限风光尽被占。', '采得百花成蜜后，', '为谁辛苦为谁甜？'],
    grade: 4,
  },

  // ===== 五年级 =====
  {
    id: 'g5-01',
    title: '示儿',
    author: '陆游',
    dynasty: '宋',
    content: ['死去元知万事空，', '但悲不见九州同。', '王师北定中原日，', '家祭无忘告乃翁。'],
    grade: 5,
  },
  {
    id: 'g5-02',
    title: '题临安邸',
    author: '林升',
    dynasty: '宋',
    content: ['山外青山楼外楼，', '西湖歌舞几时休？', '暖风熏得游人醉，', '直把杭州作汴州。'],
    grade: 5,
  },
  {
    id: 'g5-03',
    title: '己亥杂诗',
    author: '龚自珍',
    dynasty: '清',
    content: ['九州生气恃风雷，', '万马齐喑究可哀。', '我劝天公重抖擞，', '不拘一格降人才。'],
    grade: 5,
  },
  {
    id: 'g5-04',
    title: '山居秋暝',
    author: '王维',
    dynasty: '唐',
    content: ['空山新雨后，', '天气晚来秋。', '明月松间照，', '清泉石上流。'],
    grade: 5,
  },
  {
    id: 'g5-05',
    title: '枫桥夜泊',
    author: '张继',
    dynasty: '唐',
    content: ['月落乌啼霜满天，', '江枫渔火对愁眠。', '姑苏城外寒山寺，', '夜半钟声到客船。'],
    grade: 5,
  },
  {
    id: 'g5-06',
    title: '长相思',
    author: '纳兰性德',
    dynasty: '清',
    content: ['山一程，水一程，', '身向榆关那畔行，', '夜深千帐灯。', '风一更，雪一更，', '聒碎乡心梦不成，', '故园无此声。'],
    grade: 5,
  },
  {
    id: 'g5-07',
    title: '渔歌子',
    author: '张志和',
    dynasty: '唐',
    content: ['西塞山前白鹭飞，', '桃花流水鳜鱼肥。', '青箬笠，绿蓑衣，', '斜风细雨不须归。'],
    grade: 5,
  },
  {
    id: 'g5-08',
    title: '观书有感',
    author: '朱熹',
    dynasty: '宋',
    content: ['半亩方塘一鉴开，', '天光云影共徘徊。', '问渠那得清如许？', '为有源头活水来。'],
    grade: 5,
  },
  {
    id: 'g5-09',
    title: '乡村四月',
    author: '翁卷',
    dynasty: '宋',
    content: ['绿遍山原白满川，', '子规声里雨如烟。', '乡村四月闲人少，', '才了蚕桑又插田。'],
    grade: 5,
  },
  {
    id: 'g5-10',
    title: '四时田园杂兴（其二十五）',
    author: '范成大',
    dynasty: '宋',
    content: ['梅子金黄杏子肥，', '麦花雪白菜花稀。', '日长篱落无人过，', '惟有蜻蜓蛱蝶飞。'],
    grade: 5,
  },

  // ===== 六年级 =====
  {
    id: 'g6-01',
    title: '七步诗',
    author: '曹植',
    dynasty: '三国',
    content: ['煮豆持作羹，', '漉豉以为汁。', '萁在釜下燃，', '豆在釜中泣。', '本自同根生，', '相煎何太急？'],
    grade: 6,
  },
  {
    id: 'g6-02',
    title: '鸟鸣涧',
    author: '王维',
    dynasty: '唐',
    content: ['人闲桂花落，', '夜静春山空。', '月出惊山鸟，', '时鸣春涧中。'],
    grade: 6,
  },
  {
    id: 'g6-03',
    title: '石灰吟',
    author: '于谦',
    dynasty: '明',
    content: ['千锤万凿出深山，', '烈火焚烧若等闲。', '粉骨碎身浑不怕，', '要留清白在人间。'],
    grade: 6,
  },
  {
    id: 'g6-04',
    title: '竹石',
    author: '郑燮',
    dynasty: '清',
    content: ['咬定青山不放松，', '立根原在破岩中。', '千磨万击还坚劲，', '任尔东西南北风。'],
    grade: 6,
  },
  {
    id: 'g6-05',
    title: '闻官军收河南河北',
    author: '杜甫',
    dynasty: '唐',
    content: ['剑外忽传收蓟北，', '初闻涕泪满衣裳。', '却看妻子愁何在，', '漫卷诗书喜欲狂。', '白日放歌须纵酒，', '青春作伴好还乡。', '即从巴峡穿巫峡，', '便下襄阳向洛阳。'],
    grade: 6,
  },
  {
    id: 'g6-06',
    title: '己亥杂诗',
    author: '龚自珍',
    dynasty: '清',
    content: ['浩荡离愁白日斜，', '吟鞭东指即天涯。', '落红不是无情物，', '化作春泥更护花。'],
    grade: 6,
  },
  {
    id: 'g6-07',
    title: '浣溪沙',
    author: '苏轼',
    dynasty: '宋',
    content: ['游蕲水清泉寺，寺临兰溪，溪水西流。', '山下兰芽短浸溪，', '松间沙路净无泥，', '潇潇暮雨子规啼。', '谁道人生无再少？', '门前流水尚能西！', '休将白发唱黄鸡。'],
    grade: 6,
  },
  {
    id: 'g6-08',
    title: '卜算子·送鲍浩然之浙东',
    author: '王观',
    dynasty: '宋',
    content: ['水是眼波横，', '山是眉峰聚。', '欲问行人去那边？', '眉眼盈盈处。', '才始送春归，', '又送君归去。', '若到江南赶上春，', '千万和春住。'],
    grade: 6,
  },
  {
    id: 'g6-09',
    title: '马诗',
    author: '李贺',
    dynasty: '唐',
    content: ['大漠沙如雪，', '燕山月似钩。', '何当金络脑，', '快走踏清秋。'],
    grade: 6,
  },
  {
    id: 'g6-10',
    title: '泊船瓜洲',
    author: '王安石',
    dynasty: '宋',
    content: ['京口瓜洲一水间，', '钟山只隔数重山。', '春风又绿江南岸，', '明月何时照我还？'],
    grade: 6,
  },
];

/** 按年级分组 */
export const poemsByGrade = (grade: number) => poems.filter(p => p.grade === grade);

/** 年级标签配置 */
export const gradeGroups = [
  { label: '1-2年级', grades: [1, 2] },
  { label: '3-4年级', grades: [3, 4] },
  { label: '5-6年级', grades: [5, 6] },
];
