/**
 * 单元测试卷题库数据 - 人教版小学数学
 * 按年级、学期、单元组织，每个单元至少8道题
 */

export interface UnitQuestion {
  id: string;
  unitName: string;
  grade: number;
  semester: '上' | '下';
  questions: {
    type: string;
    content: string;
    answer: string;
    difficulty: 1 | 2 | 3;
  }[];
}

export const unitTestData: UnitQuestion[] = [
  // ==================== 一年级上册 ====================
  {
    id: 'g1s-u1',
    unitName: '准备课',
    grade: 1,
    semester: '上',
    questions: [
      { type: '填空题', content: '数一数，图中有（  ）朵花。\n（图略：5朵花）', answer: '5', difficulty: 1 },
      { type: '填空题', content: '在多的后面画"√"。\n△△△    ○○○○', answer: '○○○○ 后面画√', difficulty: 1 },
      { type: '填空题', content: '在少的后面画"○"。\n☆☆☆☆☆    □□', answer: '□□ 后面画○', difficulty: 1 },
      { type: '填空题', content: '把同样多的用线连起来。\n3个苹果    3个橘子', answer: '连线：3个苹果连3个橘子', difficulty: 1 },
      { type: '选择题', content: '下面哪种水果最多？\nA. 2个苹果  B. 5个香蕉  C. 3个橘子', answer: 'B', difficulty: 1 },
      { type: '选择题', content: '4和6中间的数是（  ）。\nA. 3  B. 5  C. 7', answer: 'B', difficulty: 2 },
      { type: '判断题', content: '3比4多。（  ）', answer: '×', difficulty: 1 },
      { type: '判断题', content: '5和5一样多。（  ）', answer: '√', difficulty: 1 },
      { type: '填空题', content: '从大到小排列：2、5、1、4、3\n（  ）>（  ）>（  ）>（  ）>（  ）', answer: '5 > 4 > 3 > 2 > 1', difficulty: 2 },
      { type: '填空题', content: '从1数到10，6的后面是（  ），前面是（  ）。', answer: '7；5', difficulty: 2 },
    ],
  },
  {
    id: 'g1s-u2',
    unitName: '位置',
    grade: 1,
    semester: '上',
    questions: [
      { type: '填空题', content: '小明前面有3人，后面有2人，这一排一共有（  ）人。', answer: '6', difficulty: 2 },
      { type: '填空题', content: '看图填空：小鸟在小狗的（  ）面，小狗在小鸟的（  ）面。\n（小鸟在上，小狗在下）', answer: '上；下', difficulty: 1 },
      { type: '选择题', content: '小华站在队伍的第3个，他前面有（  ）人。\nA. 1人  B. 2人  C. 3人', answer: 'B', difficulty: 1 },
      { type: '选择题', content: '从左数，第4个是△：○△□○△□\n从右数，△排在第（  ）个。\nA. 2  B. 3  C. 4', answer: 'B', difficulty: 2 },
      { type: '判断题', content: '面对太阳，你的前面是东面。（  ）', answer: '√', difficulty: 2 },
      { type: '判断题', content: '小猫在小狗的左边，那么小狗在小猫的右边。（  ）', answer: '√', difficulty: 1 },
      { type: '填空题', content: '小红住在小明楼上，小明住在小红（  ）面。', answer: '下', difficulty: 1 },
      { type: '应用题', content: '一排小朋友，从左往右数小明排第5，从右往左数小明排第4，这排一共有几个小朋友？', answer: '5+4-1=8（个）', difficulty: 3 },
      { type: '填空题', content: '书桌的上面放着书，书的（  ）面是书桌。', answer: '下', difficulty: 1 },
      { type: '应用题', content: '小明的前面有4个人，后面有5个人，从前面数小明排第几？', answer: '第5', difficulty: 2 },
    ],
  },
  {
    id: 'g1s-u3',
    unitName: '1-5的认识和加减法',
    grade: 1,
    semester: '上',
    questions: [
      { type: '计算题', content: '1 + 2 =', answer: '3', difficulty: 1 },
      { type: '计算题', content: '3 + 1 =', answer: '4', difficulty: 1 },
      { type: '计算题', content: '5 - 2 =', answer: '3', difficulty: 1 },
      { type: '计算题', content: '4 - 1 =', answer: '3', difficulty: 1 },
      { type: '计算题', content: '2 + 3 =', answer: '5', difficulty: 1 },
      { type: '计算题', content: '5 - 3 =', answer: '2', difficulty: 1 },
      { type: '填空题', content: '3 +（  ）= 5', answer: '2', difficulty: 2 },
      { type: '填空题', content: '（  ）- 2 = 3', answer: '5', difficulty: 2 },
      { type: '比较大小', content: '在○里填上">"、"<"或"="。\n3 + 1 ○ 5', answer: '<', difficulty: 2 },
      { type: '应用题', content: '树上有3只小鸟，又飞来了2只，现在一共有几只小鸟？', answer: '3+2=5（只）', difficulty: 2 },
      { type: '应用题', content: '小明有5个苹果，吃了2个，还剩几个？', answer: '5-2=3（个）', difficulty: 2 },
      { type: '计算题', content: '1 + 1 + 1 =', answer: '3', difficulty: 2 },
    ],
  },
  {
    id: 'g1s-u4',
    unitName: '6-10的认识和加减法',
    grade: 1,
    semester: '上',
    questions: [
      { type: '计算题', content: '4 + 3 =', answer: '7', difficulty: 1 },
      { type: '计算题', content: '6 + 2 =', answer: '8', difficulty: 1 },
      { type: '计算题', content: '9 - 4 =', answer: '5', difficulty: 1 },
      { type: '计算题', content: '10 - 3 =', answer: '7', difficulty: 1 },
      { type: '计算题', content: '5 + 5 =', answer: '10', difficulty: 1 },
      { type: '计算题', content: '8 - 6 =', answer: '2', difficulty: 1 },
      { type: '填空题', content: '6 +（  ）= 10', answer: '4', difficulty: 2 },
      { type: '填空题', content: '（  ）- 3 = 7', answer: '10', difficulty: 2 },
      { type: '比较大小', content: '在○里填上">"、"<"或"="。\n5 + 3 ○ 9', answer: '<', difficulty: 2 },
      { type: '应用题', content: '池塘里有6只青蛙，跳走了3只，还剩几只？', answer: '6-3=3（只）', difficulty: 2 },
      { type: '应用题', content: '小红有4朵红花和5朵黄花，一共有几朵花？', answer: '4+5=9（朵）', difficulty: 2 },
      { type: '计算题', content: '2 + 3 + 4 =', answer: '9', difficulty: 2 },
    ],
  },
  {
    id: 'g1s-u5',
    unitName: '11-20各数的认识',
    grade: 1,
    semester: '上',
    questions: [
      { type: '填空题', content: '1个十和5个一组成（  ）。', answer: '15', difficulty: 1 },
      { type: '填空题', content: '20里面有（  ）个十。', answer: '2', difficulty: 1 },
      { type: '填空题', content: '18的十位上是（  ），个位上是（  ）。', answer: '1；8', difficulty: 1 },
      { type: '填空题', content: '与16相邻的两个数是（  ）和（  ）。', answer: '15；17', difficulty: 2 },
      { type: '计算题', content: '10 + 5 =', answer: '15', difficulty: 1 },
      { type: '计算题', content: '18 - 10 =', answer: '8', difficulty: 1 },
      { type: '计算题', content: '12 + 6 =', answer: '18', difficulty: 1 },
      { type: '计算题', content: '17 - 7 =', answer: '10', difficulty: 1 },
      { type: '比较大小', content: '在○里填上">"、"<"或"="。\n12 ○ 15', answer: '<', difficulty: 1 },
      { type: '应用题', content: '小明有10支铅笔，妈妈又给他买了5支，现在一共有多少支？', answer: '10+5=15（支）', difficulty: 2 },
      { type: '填空题', content: '从大到小排列：11、18、14、20、16\n（  ）>（  ）>（  ）>（  ）>（  ）', answer: '20 > 18 > 16 > 14 > 11', difficulty: 2 },
      { type: '填空题', content: '个位上是3的两位数有（  ）、（  ）、（  ）。（从小到大写三个）', answer: '13、23、33', difficulty: 3 },
    ],
  },

  // ==================== 一年级下册 ====================
  {
    id: 'g1x-u1',
    unitName: '认识图形（二）',
    grade: 1,
    semester: '下',
    questions: [
      { type: '填空题', content: '长方形有（  ）条边，（  ）个角。', answer: '4；4', difficulty: 1 },
      { type: '填空题', content: '正方形有（  ）条边，每条边都（  ）。', answer: '4；相等', difficulty: 1 },
      { type: '填空题', content: '三角形有（  ）条边，（  ）个角。', answer: '3；3', difficulty: 1 },
      { type: '选择题', content: '下面哪个是正方形？\nA. 长长方方的  B. 四条边一样长  C. 三个角', answer: 'B', difficulty: 1 },
      { type: '选择题', content: '用4根小棒可以拼成一个（  ）。\nA. 三角形  B. 正方形  C. 圆', answer: 'B', difficulty: 1 },
      { type: '判断题', content: '长方形和正方形的四个角都是直角。（  ）', answer: '√', difficulty: 2 },
      { type: '判断题', content: '圆没有角。（  ）', answer: '√', difficulty: 1 },
      { type: '填空题', content: '硬币的面是（  ）形。', answer: '圆', difficulty: 1 },
      { type: '应用题', content: '用3根同样长的小棒可以拼成一个什么图形？', answer: '三角形', difficulty: 1 },
      { type: '填空题', content: '长方形对边（  ），正方形四条边都（  ）。', answer: '相等；相等', difficulty: 2 },
    ],
  },
  {
    id: 'g1x-u2',
    unitName: '20以内的退位减法',
    grade: 1,
    semester: '下',
    questions: [
      { type: '计算题', content: '12 - 5 =', answer: '7', difficulty: 1 },
      { type: '计算题', content: '15 - 8 =', answer: '7', difficulty: 1 },
      { type: '计算题', content: '17 - 9 =', answer: '8', difficulty: 1 },
      { type: '计算题', content: '13 - 6 =', answer: '7', difficulty: 1 },
      { type: '计算题', content: '11 - 4 =', answer: '7', difficulty: 1 },
      { type: '计算题', content: '16 - 7 =', answer: '9', difficulty: 1 },
      { type: '计算题', content: '14 - 9 =', answer: '5', difficulty: 1 },
      { type: '计算题', content: '18 - 9 =', answer: '9', difficulty: 1 },
      { type: '填空题', content: '（  ）+ 7 = 15', answer: '8', difficulty: 2 },
      { type: '填空题', content: '13 -（  ）= 6', answer: '7', difficulty: 2 },
      { type: '应用题', content: '树上有15只鸟，飞走了8只，还剩几只？', answer: '15-8=7（只）', difficulty: 2 },
      { type: '应用题', content: '小明有12颗糖，吃了9颗，还剩几颗？', answer: '12-9=3（颗）', difficulty: 2 },
    ],
  },
  {
    id: 'g1x-u3',
    unitName: '100以内数的认识',
    grade: 1,
    semester: '下',
    questions: [
      { type: '填空题', content: '3个十和5个一组成（  ）。', answer: '35', difficulty: 1 },
      { type: '填空题', content: '68里面有（  ）个十和（  ）个一。', answer: '6；8', difficulty: 1 },
      { type: '填空题', content: '100里面有（  ）个十。', answer: '10', difficulty: 1 },
      { type: '填空题', content: '个位上是7，十位上是4的数是（  ）。', answer: '47', difficulty: 1 },
      { type: '计算题', content: '30 + 5 =', answer: '35', difficulty: 1 },
      { type: '计算题', content: '46 - 6 =', answer: '40', difficulty: 1 },
      { type: '计算题', content: '20 + 30 =', answer: '50', difficulty: 1 },
      { type: '计算题', content: '58 - 50 =', answer: '8', difficulty: 1 },
      { type: '比较大小', content: '在○里填上">"、"<"或"="。\n45 ○ 54', answer: '<', difficulty: 2 },
      { type: '比较大小', content: '在○里填上">"、"<"或"="。\n78 ○ 75', answer: '>', difficulty: 2 },
      { type: '应用题', content: '学校有30个篮球，又买了20个，现在一共有多少个？', answer: '30+20=50（个）', difficulty: 2 },
      { type: '填空题', content: '与69相邻的两个数是（  ）和（  ）。', answer: '68；70', difficulty: 2 },
    ],
  },

  // ==================== 二年级上册 ====================
  {
    id: 'g2s-u1',
    unitName: '长度单位',
    grade: 2,
    semester: '上',
    questions: [
      { type: '填空题', content: '1米 =（  ）厘米', answer: '100', difficulty: 1 },
      { type: '填空题', content: '课桌高约70（  ）。（填"米"或"厘米"）', answer: '厘米', difficulty: 1 },
      { type: '填空题', content: '教室的长约8（  ）。（填"米"或"厘米"）', answer: '米', difficulty: 1 },
      { type: '选择题', content: '下面哪个物体的长度最接近1米？\nA. 铅笔  B. 课桌  C. 教室的门', answer: 'B', difficulty: 2 },
      { type: '选择题', content: '一根绳子对折后是5米，这根绳子原来长（  ）米。\nA. 5  B. 10  C. 15', answer: 'B', difficulty: 2 },
      { type: '计算题', content: '3米 - 100厘米 =（  ）米', answer: '2', difficulty: 2 },
      { type: '计算题', content: '200厘米 =（  ）米', answer: '2', difficulty: 1 },
      { type: '计算题', content: '1米50厘米 + 50厘米 =（  ）米', answer: '2', difficulty: 2 },
      { type: '判断题', content: '1米比100厘米长。（  ）', answer: '×', difficulty: 1 },
      { type: '应用题', content: '小明身高1米20厘米，小华比小明高10厘米，小华身高多少？', answer: '1米30厘米（或130厘米）', difficulty: 2 },
      { type: '应用题', content: '一根铁丝长80厘米，剪去30厘米，还剩多少厘米？', answer: '80-30=50（厘米）', difficulty: 2 },
      { type: '填空题', content: '量比较短的物体，可以用（  ）作单位。', answer: '厘米', difficulty: 1 },
    ],
  },
  {
    id: 'g2s-u2',
    unitName: '100以内的加法和减法（二）',
    grade: 2,
    semester: '上',
    questions: [
      { type: '计算题', content: '36 + 47 =', answer: '83', difficulty: 1 },
      { type: '计算题', content: '53 + 29 =', answer: '82', difficulty: 1 },
      { type: '计算题', content: '80 - 36 =', answer: '44', difficulty: 1 },
      { type: '计算题', content: '72 - 45 =', answer: '27', difficulty: 1 },
      { type: '计算题', content: '45 + 38 =', answer: '83', difficulty: 1 },
      { type: '计算题', content: '90 - 56 =', answer: '34', difficulty: 1 },
      { type: '竖式计算', content: '用竖式计算：\n  56\n+ 37\n------', answer: '93', difficulty: 2 },
      { type: '竖式计算', content: '用竖式计算：\n  83\n- 47\n------', answer: '36', difficulty: 2 },
      { type: '应用题', content: '图书馆有故事书45本，科技书38本，一共有多少本？', answer: '45+38=83（本）', difficulty: 2 },
      { type: '应用题', content: '停车场有65辆车，开走了28辆，还剩多少辆？', answer: '65-28=37（辆）', difficulty: 2 },
      { type: '应用题', content: '一年级有42人，二年级有39人，两个年级一共有多少人？', answer: '42+39=81（人）', difficulty: 2 },
      { type: '比较大小', content: '在○里填上">"、"<"或"="。\n36 + 28 ○ 55', answer: '>', difficulty: 2 },
    ],
  },
  {
    id: 'g2s-u3',
    unitName: '角的初步认识',
    grade: 2,
    semester: '上',
    questions: [
      { type: '填空题', content: '一个角有（  ）个顶点和（  ）条边。', answer: '1；2', difficulty: 1 },
      { type: '填空题', content: '角的大小与边的（  ）无关，与两条边张开的（  ）有关。', answer: '长短；大小', difficulty: 2 },
      { type: '选择题', content: '下面哪个图形是角？\nA. ○  B. △  C. □的角', answer: 'C', difficulty: 1 },
      { type: '判断题', content: '角的两条边越长，角就越大。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '直角是最大的角。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '三角板上的直角和黑板上的直角一样大。（  ）', answer: '√', difficulty: 2 },
      { type: '填空题', content: '长方形有（  ）个直角，正方形有（  ）个直角。', answer: '4；4', difficulty: 1 },
      { type: '填空题', content: '三角板上有（  ）个角，其中最大的角是（  ）角。', answer: '3；直', difficulty: 2 },
      { type: '选择题', content: '一个角的两条边张开得越大，角就越（  ）。\nA. 大  B. 小  C. 不变', answer: 'A', difficulty: 1 },
      { type: '应用题', content: '一张长方形纸剪去一个角，还剩几个角？（写出一种情况即可）', answer: '3个、4个或5个（写出一种即可）', difficulty: 3 },
    ],
  },

  // ==================== 二年级下册 ====================
  {
    id: 'g2x-u1',
    unitName: '数据收集整理',
    grade: 2,
    semester: '下',
    questions: [
      { type: '填空题', content: '统计表可以帮助我们清楚地看出数据的（  ）。', answer: '多少', difficulty: 1 },
      { type: '应用题', content: '二（1）班同学最喜欢的颜色统计如下：\n红色8人，蓝色12人，绿色6人，黄色4人。\n（1）喜欢（  ）色的人最多。\n（2）喜欢蓝色的比喜欢红色的多（  ）人。', answer: '（1）蓝；（2）4', difficulty: 2 },
      { type: '应用题', content: '下面是某班同学最喜欢吃的水果统计：\n苹果10人，香蕉8人，橘子5人，葡萄7人。\n（1）一共调查了（  ）人。\n（2）最喜欢吃（  ）的人最少。', answer: '（1）30；（2）橘子', difficulty: 2 },
      { type: '选择题', content: '统计同学们最喜欢的运动，应该用（  ）来记录。\nA. 画图  B. 列表  C. 画正字', answer: 'C', difficulty: 1 },
      { type: '判断题', content: '统计的时候，一个正字代表5个人。（  ）', answer: '√', difficulty: 1 },
      { type: '填空题', content: '"正"字一共有（  ）笔，一笔代表（  ）个。', answer: '5；1', difficulty: 1 },
      { type: '应用题', content: '动物园里有猴子15只，熊猫8只，老虎6只，大象4只。\n（1）猴子比熊猫多几只？\n（2）熊猫和老虎一共有几只？', answer: '（1）15-8=7（只）；（2）8+6=14（只）', difficulty: 2 },
      { type: '填空题', content: '用画"正"字的方法统计，"正正"表示（  ）个。', answer: '10', difficulty: 1 },
      { type: '应用题', content: '学校门口5分钟内通过的车辆统计：\n小汽车12辆，自行车8辆，公交车4辆，摩托车6辆。\n哪种车最多？多几辆？', answer: '小汽车最多，比自行车多4辆', difficulty: 2 },
      { type: '选择题', content: '要调查全班同学最喜欢哪个季节，最好的方法是（  ）。\nA. 问老师  B. 举手统计  C. 猜一猜', answer: 'B', difficulty: 1 },
    ],
  },
  {
    id: 'g2x-u2',
    unitName: '表内除法（一）',
    grade: 2,
    semester: '下',
    questions: [
      { type: '计算题', content: '6 ÷ 2 =', answer: '3', difficulty: 1 },
      { type: '计算题', content: '12 ÷ 3 =', answer: '4', difficulty: 1 },
      { type: '计算题', content: '15 ÷ 5 =', answer: '3', difficulty: 1 },
      { type: '计算题', content: '18 ÷ 6 =', answer: '3', difficulty: 1 },
      { type: '计算题', content: '24 ÷ 4 =', answer: '6', difficulty: 1 },
      { type: '计算题', content: '20 ÷ 5 =', answer: '4', difficulty: 1 },
      { type: '计算题', content: '36 ÷ 6 =', answer: '6', difficulty: 1 },
      { type: '计算题', content: '30 ÷ 5 =', answer: '6', difficulty: 1 },
      { type: '填空题', content: '把12个苹果平均分成3份，每份（  ）个。', answer: '4', difficulty: 1 },
      { type: '填空题', content: '24里面有（  ）个4。', answer: '6', difficulty: 2 },
      { type: '应用题', content: '有18个橘子，平均分给6个小朋友，每人分几个？', answer: '18÷6=3（个）', difficulty: 2 },
      { type: '应用题', content: '有20朵花，每4朵扎一束，可以扎几束？', answer: '20÷4=5（束）', difficulty: 2 },
    ],
  },
  {
    id: 'g2x-u3',
    unitName: '混合运算',
    grade: 2,
    semester: '下',
    questions: [
      { type: '计算题', content: '5 + 3 × 2 =', answer: '11', difficulty: 1 },
      { type: '计算题', content: '12 - 4 × 2 =', answer: '4', difficulty: 1 },
      { type: '计算题', content: '(6 + 3) × 2 =', answer: '18', difficulty: 2 },
      { type: '计算题', content: '15 ÷ 3 + 4 =', answer: '9', difficulty: 1 },
      { type: '计算题', content: '20 - 12 ÷ 4 =', answer: '17', difficulty: 1 },
      { type: '计算题', content: '(18 - 6) ÷ 3 =', answer: '4', difficulty: 2 },
      { type: '计算题', content: '4 × 5 - 10 =', answer: '10', difficulty: 1 },
      { type: '计算题', content: '24 ÷ (6 - 2) =', answer: '6', difficulty: 2 },
      { type: '判断题', content: '5 + 3 × 2 = 16。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '在没有括号的算式里，要先算乘除法，再算加减法。（  ）', answer: '√', difficulty: 1 },
      { type: '应用题', content: '小明买了3本笔记本，每本4元，付了20元，应找回多少元？', answer: '20-3×4=8（元）', difficulty: 2 },
      { type: '应用题', content: '有24个苹果，吃了6个，剩下的平均分给3个人，每人分几个？', answer: '(24-6)÷3=6（个）', difficulty: 3 },
    ],
  },

  // ==================== 三年级上册 ====================
  {
    id: 'g3s-u1',
    unitName: '时、分、秒',
    grade: 3,
    semester: '上',
    questions: [
      { type: '填空题', content: '1时 =（  ）分', answer: '60', difficulty: 1 },
      { type: '填空题', content: '1分 =（  ）秒', answer: '60', difficulty: 1 },
      { type: '填空题', content: '1时 =（  ）秒', answer: '3600', difficulty: 2 },
      { type: '填空题', content: '120秒 =（  ）分', answer: '2', difficulty: 1 },
      { type: '填空题', content: '3时 =（  ）分', answer: '180', difficulty: 1 },
      { type: '计算题', content: '2时30分 + 40分 =（  ）时（  ）分', answer: '3；10', difficulty: 2 },
      { type: '计算题', content: '5分 - 180秒 =（  ）分', answer: '2', difficulty: 2 },
      { type: '选择题', content: '小明跑50米用了9（  ）。\nA. 时  B. 分  C. 秒', answer: 'C', difficulty: 1 },
      { type: '判断题', content: '秒针走一圈是60秒，也就是1分。（  ）', answer: '√', difficulty: 1 },
      { type: '判断题', content: '时针从数字3走到数字6，经过了3小时。（  ）', answer: '×', difficulty: 2 },
      { type: '应用题', content: '一场电影从下午2时开始，到下午4时30分结束，这场电影放映了多长时间？', answer: '2时30分', difficulty: 2 },
      { type: '应用题', content: '小红7:30从家出发，走了25分钟到学校，她几点到学校？', answer: '7:55', difficulty: 2 },
    ],
  },
  {
    id: 'g3s-u2',
    unitName: '万以内的加法和减法（一）',
    grade: 3,
    semester: '上',
    questions: [
      { type: '计算题', content: '230 + 450 =', answer: '680', difficulty: 1 },
      { type: '计算题', content: '560 - 280 =', answer: '280', difficulty: 1 },
      { type: '计算题', content: '370 + 480 =', answer: '850', difficulty: 1 },
      { type: '计算题', content: '800 - 350 =', answer: '450', difficulty: 1 },
      { type: '计算题', content: '125 + 367 =', answer: '492', difficulty: 2 },
      { type: '计算题', content: '603 - 245 =', answer: '358', difficulty: 2 },
      { type: '竖式计算', content: '用竖式计算：\n  456\n+ 378\n------', answer: '834', difficulty: 2 },
      { type: '竖式计算', content: '用竖式计算：\n  702\n- 385\n------', answer: '317', difficulty: 2 },
      { type: '应用题', content: '学校图书馆有故事书350本，科技书280本，一共有多少本？', answer: '350+280=630（本）', difficulty: 2 },
      { type: '应用题', content: '水果店有苹果500千克，卖出235千克，还剩多少千克？', answer: '500-235=265（千克）', difficulty: 2 },
      { type: '估算题', content: '估算：398 + 204 ≈（  ）', answer: '600', difficulty: 2 },
      { type: '估算题', content: '估算：603 - 297 ≈（  ）', answer: '300', difficulty: 2 },
    ],
  },
  {
    id: 'g3s-u3',
    unitName: '倍的认识',
    grade: 3,
    semester: '上',
    questions: [
      { type: '填空题', content: '5的3倍是（  ）。', answer: '15', difficulty: 1 },
      { type: '填空题', content: '24是6的（  ）倍。', answer: '4', difficulty: 1 },
      { type: '填空题', content: '（  ）的4倍是20。', answer: '5', difficulty: 2 },
      { type: '选择题', content: '小明有6颗糖，小红的糖是小明的3倍，小红有（  ）颗糖。\nA. 9  B. 18  C. 3', answer: 'B', difficulty: 1 },
      { type: '选择题', content: '鸡有8只，鸭的只数是鸡的2倍，鸭有（  ）只。\nA. 4  B. 10  C. 16', answer: 'C', difficulty: 1 },
      { type: '应用题', content: '动物园里有猴子8只，大熊猫的只数是猴子的3倍，大熊猫有多少只？', answer: '8×3=24（只）', difficulty: 2 },
      { type: '应用题', content: '小红有12朵花，小兰的花是小红的一半，小兰有几朵花？', answer: '12÷2=6（朵）', difficulty: 2 },
      { type: '应用题', content: '爸爸今年36岁，是小明年龄的4倍，小明今年几岁？', answer: '36÷4=9（岁）', difficulty: 2 },
      { type: '应用题', content: '果园里有梨树15棵，苹果树是梨树的3倍，苹果树比梨树多多少棵？', answer: '15×3-15=30（棵）', difficulty: 3 },
      { type: '比较大小', content: '在○里填上">"、"<"或"="。\n4的5倍 ○ 5的4倍', answer: '=', difficulty: 2 },
      { type: '应用题', content: '一支钢笔8元，一支铅笔的价钱是钢笔的2倍少3元，一支铅笔多少元？', answer: '8×2-3=13（元）', difficulty: 3 },
      { type: '填空题', content: '一个数的5倍是35，这个数是（  ）。', answer: '7', difficulty: 2 },
    ],
  },

  // ==================== 三年级下册 ====================
  {
    id: 'g3x-u1',
    unitName: '位置与方向（一）',
    grade: 3,
    semester: '下',
    questions: [
      { type: '填空题', content: '早晨起来，面向太阳，前面是（  ），后面是（  ），左面是（  ），右面是（  ）。', answer: '东；西；北；南', difficulty: 1 },
      { type: '填空题', content: '地图通常是按上（  ）、下（  ）、左（  ）、右（  ）绘制的。', answer: '北；南；西；东', difficulty: 1 },
      { type: '选择题', content: '小明的家在学校的东面，那么学校在小明家的（  ）面。\nA. 东  B. 西  C. 南', answer: 'B', difficulty: 1 },
      { type: '选择题', content: '图书馆在教学楼的东北方向，教学楼在图书馆的（  ）方向。\nA. 东北  B. 西南  C. 东南', answer: 'B', difficulty: 2 },
      { type: '判断题', content: '南和北是相对的方向。（  ）', answer: '√', difficulty: 1 },
      { type: '判断题', content: '面对北方，右手边是东方。（  ）', answer: '√', difficulty: 1 },
      { type: '判断题', content: '西北方向在北和西之间。（  ）', answer: '√', difficulty: 1 },
      { type: '应用题', content: '小明从家出发，先向东走200米到学校，再向北走300米到图书馆。请描述从图书馆回家的路线。', answer: '先向南走300米到学校，再向西走200米到家', difficulty: 3 },
      { type: '填空题', content: '东北方向和（  ）方向相对。', answer: '西南', difficulty: 2 },
      { type: '应用题', content: '看图回答：小兔在小猫的南面，小狗在小猫的东面，那么小兔在小狗的（  ）面。', answer: '西南', difficulty: 3 },
    ],
  },
  {
    id: 'g3x-u2',
    unitName: '除数是一位数的除法',
    grade: 3,
    semester: '下',
    questions: [
      { type: '计算题', content: '84 ÷ 4 =', answer: '21', difficulty: 1 },
      { type: '计算题', content: '96 ÷ 3 =', answer: '32', difficulty: 1 },
      { type: '计算题', content: '75 ÷ 5 =', answer: '15', difficulty: 1 },
      { type: '计算题', content: '68 ÷ 2 =', answer: '34', difficulty: 1 },
      { type: '计算题', content: '144 ÷ 6 =', answer: '24', difficulty: 2 },
      { type: '计算题', content: '205 ÷ 5 =', answer: '41', difficulty: 2 },
      { type: '计算题', content: '312 ÷ 3 =', answer: '104', difficulty: 2 },
      { type: '计算题', content: '450 ÷ 9 =', answer: '50', difficulty: 2 },
      { type: '竖式计算', content: '用竖式计算：\n  96\n÷  4\n------', answer: '24', difficulty: 2 },
      { type: '竖式计算', content: '用竖式计算：\n  78\n÷  3\n------', answer: '26', difficulty: 2 },
      { type: '应用题', content: '学校买了156本课外书，平均分给3个年级，每个年级分多少本？', answer: '156÷3=52（本）', difficulty: 2 },
      { type: '应用题', content: '一箱苹果重24千克，4箱苹果重多少千克？', answer: '24×4=96（千克）', difficulty: 2 },
      { type: '应用题', content: '有425个乒乓球，每5个装一盒，可以装多少盒？还剩几个？', answer: '425÷5=85（盒），不剩', difficulty: 3 },
    ],
  },
  {
    id: 'g3x-u3',
    unitName: '面积',
    grade: 3,
    semester: '下',
    questions: [
      { type: '填空题', content: '长方形的面积 =（  ）×（  ）', answer: '长；宽', difficulty: 1 },
      { type: '填空题', content: '正方形的面积 =（  ）×（  ）', answer: '边长；边长', difficulty: 1 },
      { type: '填空题', content: '1平方米 =（  ）平方分米', answer: '100', difficulty: 1 },
      { type: '填空题', content: '1平方分米 =（  ）平方厘米', answer: '100', difficulty: 1 },
      { type: '计算题', content: '一个长方形，长8厘米，宽5厘米，面积是多少？', answer: '8×5=40（平方厘米）', difficulty: 1 },
      { type: '计算题', content: '一个正方形，边长6分米，面积是多少？', answer: '6×6=36（平方分米）', difficulty: 1 },
      { type: '计算题', content: '一个长方形，长12米，宽8米，周长是多少？', answer: '(12+8)×2=40（米）', difficulty: 2 },
      { type: '选择题', content: '用4个边长1厘米的小正方形拼成一个大正方形，大正方形的面积是（  ）。\nA. 4平方厘米  B. 8平方厘米  C. 16平方厘米', answer: 'A', difficulty: 2 },
      { type: '判断题', content: '面积相等的长方形，周长也一定相等。（  ）', answer: '×', difficulty: 3 },
      { type: '判断题', content: '周长相等的正方形，面积一定相等。（  ）', answer: '√', difficulty: 2 },
      { type: '应用题', content: '一间教室长9米，宽6米，这间教室的面积是多少平方米？', answer: '9×6=54（平方米）', difficulty: 2 },
      { type: '应用题', content: '一块长方形菜地，长15米，宽8米。如果在菜地四周围上篱笆，篱笆长多少米？', answer: '(15+8)×2=46（米）', difficulty: 2 },
      { type: '应用题', content: '一个长方形花坛，面积是48平方米，长是8米，宽是多少米？', answer: '48÷8=6（米）', difficulty: 2 },
      { type: '计算题', content: '5平方米 =（  ）平方分米', answer: '500', difficulty: 1 },
    ],
  },

  // ==================== 四年级上册 ====================
  {
    id: 'g4s-u1',
    unitName: '大数的认识',
    grade: 4,
    semester: '上',
    questions: [
      { type: '填空题', content: '从个位起，每（  ）个数位是一级，分别是个级、万级、亿级。', answer: '四', difficulty: 1 },
      { type: '填空题', content: '10个一万是（  ），10个一百万是（  ）。', answer: '十万；一千万', difficulty: 1 },
      { type: '填空题', content: '5006000读作（  ），这个数的最高位是（  ）位。', answer: '五百万六千；百万', difficulty: 2 },
      { type: '填空题', content: '由3个亿、5个百万和2个一组成的数是（  ）。', answer: '305000002', difficulty: 2 },
      { type: '填空题', content: '把345670省略万位后面的尾数约是（  ）万。', answer: '35', difficulty: 2 },
      { type: '计算题', content: '30000 + 5000 + 400 + 70 =', answer: '35470', difficulty: 1 },
      { type: '计算题', content: '800000 - 35000 =', answer: '765000', difficulty: 1 },
      { type: '选择题', content: '下面各数中，一个零也不读的是（  ）。\nA. 3005000  B. 3050000  C. 3000500', answer: 'B', difficulty: 2 },
      { type: '判断题', content: '万级包括万位、十万位、百万位、千万位。（  ）', answer: '√', difficulty: 1 },
      { type: '判断题', content: '40506000读作四千零五十万六千。（  ）', answer: '√', difficulty: 2 },
      { type: '应用题', content: '一个数由2个亿、8个千万和5个万组成，这个数是多少？', answer: '280050000', difficulty: 2 },
      { type: '应用题', content: '某城市人口约是8960000人，省略万位后面的尾数约是多少万人？', answer: '896万人', difficulty: 2 },
    ],
  },
  {
    id: 'g4s-u2',
    unitName: '公顷和平方千米',
    grade: 4,
    semester: '上',
    questions: [
      { type: '填空题', content: '1公顷 =（  ）平方米', answer: '10000', difficulty: 1 },
      { type: '填空题', content: '1平方千米 =（  ）公顷', answer: '100', difficulty: 1 },
      { type: '填空题', content: '1平方千米 =（  ）平方米', answer: '1000000', difficulty: 2 },
      { type: '填空题', content: '5公顷 =（  ）平方米', answer: '50000', difficulty: 1 },
      { type: '填空题', content: '300公顷 =（  ）平方千米', answer: '3', difficulty: 1 },
      { type: '选择题', content: '一个足球场的面积大约是7000平方米，（  ）个这样的足球场面积约是1公顷。\nA. 7  B. 10  C. 14', answer: 'C', difficulty: 2 },
      { type: '选择题', content: '计量一个国家的面积，通常用（  ）作单位。\nA. 平方米  B. 公顷  C. 平方千米', answer: 'C', difficulty: 1 },
      { type: '判断题', content: '1公顷比1平方千米大。（  ）', answer: '×', difficulty: 1 },
      { type: '判断题', content: '边长是100米的正方形面积是1公顷。（  ）', answer: '√', difficulty: 2 },
      { type: '计算题', content: '8公顷 - 30000平方米 =（  ）平方米', answer: '50000', difficulty: 2 },
      { type: '应用题', content: '一个长方形果园，长500米，宽200米，这个果园的面积是多少公顷？', answer: '500×200=100000（平方米）=10公顷', difficulty: 3 },
      { type: '应用题', content: '一块正方形土地的面积是4公顷，它的边长是多少米？', answer: '200米', difficulty: 3 },
    ],
  },
  {
    id: 'g4s-u3',
    unitName: '角的度量',
    grade: 4,
    semester: '上',
    questions: [
      { type: '填空题', content: '线段有（  ）个端点，射线有（  ）个端点，直线（  ）端点。', answer: '两；一；没有', difficulty: 1 },
      { type: '填空题', content: '1个平角 =（  ）度 =（  ）个直角', answer: '180；2', difficulty: 1 },
      { type: '填空题', content: '1个周角 =（  ）度 =（  ）个平角', answer: '360；2', difficulty: 1 },
      { type: '填空题', content: '把线段向两端无限延伸，就得到一条（  ）。', answer: '直线', difficulty: 1 },
      { type: '填空题', content: '度量角的大小要用（  ），角的计量单位是（  ）。', answer: '量角器；度', difficulty: 1 },
      { type: '计算题', content: '一个角是35度，它是（  ）角。', answer: '锐', difficulty: 1 },
      { type: '计算题', content: '一个钝角的范围是大于（  ）度且小于（  ）度。', answer: '90；180', difficulty: 2 },
      { type: '选择题', content: '下面各角中，最大的是（  ）。\nA. 锐角  B. 直角  C. 钝角', answer: 'C', difficulty: 1 },
      { type: '判断题', content: '一条射线长5厘米。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '角的两边画得越长，角就越大。（  ）', answer: '×', difficulty: 1 },
      { type: '计算题', content: '已知∠1 = 35度，∠2 = 55度，∠1 + ∠2 =（  ）度。', answer: '90', difficulty: 2 },
      { type: '应用题', content: '把一个平角分成两个角，其中一个角是70度，另一个角是多少度？', answer: '180-70=110（度）', difficulty: 2 },
    ],
  },
  {
    id: 'g4s-u4',
    unitName: '三位数乘两位数',
    grade: 4,
    semester: '上',
    questions: [
      { type: '计算题', content: '123 × 12 =', answer: '1476', difficulty: 1 },
      { type: '计算题', content: '245 × 13 =', answer: '3185', difficulty: 1 },
      { type: '计算题', content: '306 × 24 =', answer: '7344', difficulty: 2 },
      { type: '计算题', content: '450 × 20 =', answer: '9000', difficulty: 1 },
      { type: '计算题', content: '178 × 35 =', answer: '6230', difficulty: 2 },
      { type: '计算题', content: '260 × 14 =', answer: '3640', difficulty: 1 },
      { type: '计算题', content: '408 × 25 =', answer: '10200', difficulty: 2 },
      { type: '估算题', content: '估算：298 × 31 ≈（  ）', answer: '9000', difficulty: 2 },
      { type: '估算题', content: '估算：412 × 19 ≈（  ）', answer: '8000', difficulty: 2 },
      { type: '应用题', content: '学校买了15套桌椅，每套185元，一共花了多少元？', answer: '185×15=2775（元）', difficulty: 2 },
      { type: '应用题', content: '一个果园有24行苹果树，每行126棵，这个果园一共有多少棵苹果树？', answer: '126×24=3024（棵）', difficulty: 2 },
      { type: '应用题', content: '一辆汽车从甲地开往乙地，每小时行驶85千米，行驶了12小时到达，甲乙两地相距多少千米？', answer: '85×12=1020（千米）', difficulty: 2 },
    ],
  },
  {
    id: 'g4s-u5',
    unitName: '平行四边形和梯形',
    grade: 4,
    semester: '上',
    questions: [
      { type: '填空题', content: '在同一个平面内不相交的两条直线叫做（  ），也可以说这两条直线（  ）。', answer: '平行线；互相平行', difficulty: 1 },
      { type: '填空题', content: '两条直线相交成直角，就说这两条直线互相（  ），其中一条直线是另一条直线的（  ）。', answer: '垂直；垂线', difficulty: 1 },
      { type: '填空题', content: '平行四边形有（  ）组对边分别平行，梯形只有（  ）组对边平行。', answer: '两；一', difficulty: 1 },
      { type: '填空题', content: '从平行四边形一条边上的一点到对边引一条垂线，这点和垂足之间的线段叫做平行四边形的（  ），垂足所在的边叫做平行四边形的（  ）。', answer: '高；底', difficulty: 2 },
      { type: '填空题', content: '梯形中互相平行的一组对边分别叫做梯形的（  ）和（  ）。', answer: '上底；下底', difficulty: 1 },
      { type: '判断题', content: '长方形和正方形都是特殊的平行四边形。（  ）', answer: '√', difficulty: 2 },
      { type: '判断题', content: '平行四边形是特殊的梯形。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '两条直线不相交就一定平行。（  ）', answer: '×', difficulty: 3 },
      { type: '选择题', content: '下面图形中，只有一组对边平行的是（  ）。\nA. 平行四边形  B. 长方形  C. 梯形', answer: 'C', difficulty: 1 },
      { type: '选择题', content: '过直线外一点画已知直线的平行线，可以画（  ）条。\nA. 1  B. 2  C. 无数', answer: 'A', difficulty: 2 },
      { type: '填空题', content: '两腰相等的梯形叫做（  ）梯形。', answer: '等腰', difficulty: 1 },
      { type: '判断题', content: '平行四边形的对角相等。（  ）', answer: '√', difficulty: 2 },
    ],
  },

  // ==================== 四年级下册 ====================
  {
    id: 'g4x-u1',
    unitName: '四则运算',
    grade: 4,
    semester: '下',
    questions: [
      { type: '计算题', content: '125 + 75 - 50 =', answer: '150', difficulty: 1 },
      { type: '计算题', content: '360 ÷ 9 × 4 =', answer: '160', difficulty: 1 },
      { type: '计算题', content: '200 - 36 × 4 =', answer: '56', difficulty: 2 },
      { type: '计算题', content: '(125 + 25) × 4 =', answer: '600', difficulty: 2 },
      { type: '计算题', content: '480 ÷ (16 - 4) =', answer: '40', difficulty: 2 },
      { type: '计算题', content: '72 ÷ 8 + 56 × 2 =', answer: '121', difficulty: 2 },
      { type: '计算题', content: '350 - 150 ÷ 5 × 3 =', answer: '260', difficulty: 3 },
      { type: '填空题', content: '在没有括号的算式里，如果只有加减法或者只有乘除法，都要从（  ）往（  ）按顺序计算。', answer: '左；右', difficulty: 1 },
      { type: '填空题', content: '在没有括号的算式里，有乘除法和加减法，要先算（  ）法，再算（  ）法。', answer: '乘除；加减', difficulty: 1 },
      { type: '选择题', content: '50 + 50 ÷ 5 =（  ）\nA. 20  B. 60  C. 100', answer: 'B', difficulty: 2 },
      { type: '应用题', content: '学校买了6箱乒乓球，每箱12个，每个2元，一共花了多少元？', answer: '6×12×2=144（元）', difficulty: 2 },
      { type: '应用题', content: '小明有100元，买了3本书，每本25元，还剩多少元？', answer: '100-3×25=25（元）', difficulty: 2 },
    ],
  },
  {
    id: 'g4x-u2',
    unitName: '运算定律',
    grade: 4,
    semester: '下',
    questions: [
      { type: '填空题', content: '两个数相加，交换加数的位置，（  ）不变，这叫做加法交换律。', answer: '和', difficulty: 1 },
      { type: '填空题', content: '三个数相加，先把前两个数相加，或者先把后两个数相加，（  ）不变，这叫做加法结合律。', answer: '和', difficulty: 1 },
      { type: '填空题', content: 'a × b = b × a 这是（  ）律。', answer: '乘法交换', difficulty: 1 },
      { type: '填空题', content: '(a × b) × c = a × (b × c) 这是（  ）律。', answer: '乘法结合', difficulty: 1 },
      { type: '填空题', content: 'a × (b + c) = a × b + a × c 这是（  ）律。', answer: '乘法分配', difficulty: 1 },
      { type: '计算题', content: '用简便方法计算：\n125 × 32 =', answer: '125×8×4=4000', difficulty: 2 },
      { type: '计算题', content: '用简便方法计算：\n99 × 45 =', answer: '(100-1)×45=4500-45=4455', difficulty: 2 },
      { type: '计算题', content: '用简便方法计算：\n36 × 99 + 36 =', answer: '36×(99+1)=36×100=3600', difficulty: 2 },
      { type: '计算题', content: '用简便方法计算：\n25 × (40 + 4) =', answer: '25×40+25×4=1000+100=1100', difficulty: 2 },
      { type: '计算题', content: '用简便方法计算：\n987 - 299 =', answer: '987-300+1=688', difficulty: 2 },
      { type: '判断题', content: 'a + b = b + a 运用了加法交换律。（  ）', answer: '√', difficulty: 1 },
      { type: '计算题', content: '用简便方法计算：\n72 × 125 =', answer: '9×(8×125)=9×1000=9000', difficulty: 3 },
    ],
  },
  {
    id: 'g4x-u3',
    unitName: '小数的意义和性质',
    grade: 4,
    semester: '下',
    questions: [
      { type: '填空题', content: '0.3里面有（  ）个十分之一，0.03里面有（  ）个百分之一。', answer: '3；3', difficulty: 1 },
      { type: '填空题', content: '0.8的计数单位是（  ），它有（  ）个这样的单位。', answer: '0.1（或十分之一）；8', difficulty: 1 },
      { type: '填空题', content: '3.56是由（  ）个一、（  ）个十分之一和（  ）个百分之一组成的。', answer: '3；5；6', difficulty: 2 },
      { type: '填空题', content: '把0.36的小数点向右移动两位是（  ），扩大到原来的（  ）倍。', answer: '36；100', difficulty: 2 },
      { type: '填空题', content: '把25缩小到原来的1/100是（  ）。', answer: '0.25', difficulty: 2 },
      { type: '判断题', content: '小数点的末尾添上"0"或去掉"0"，小数的大小不变。（  ）', answer: '√', difficulty: 1 },
      { type: '判断题', content: '0.8和0.80的大小相等，计数单位也相同。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '小数一定比整数小。（  ）', answer: '×', difficulty: 1 },
      { type: '选择题', content: '把3.090化简后是（  ）。\nA. 3.09  B. 3.9  C. 3.090', answer: 'A', difficulty: 1 },
      { type: '选择题', content: '与4.5相等的小数是（  ）。\nA. 4.05  B. 4.50  C. 4.500', answer: 'B', difficulty: 2 },
      { type: '计算题', content: '比较大小：0.6 ○ 0.59', answer: '>', difficulty: 1 },
      { type: '计算题', content: '把下面的数按从小到大排列：\n0.8、0.801、0.81、0.799', answer: '0.799 < 0.8 < 0.801 < 0.81', difficulty: 3 },
    ],
  },
  {
    id: 'g4x-u4',
    unitName: '三角形',
    grade: 4,
    semester: '下',
    questions: [
      { type: '填空题', content: '三角形有（  ）条边，（  ）个角，（  ）个顶点。', answer: '3；3；3', difficulty: 1 },
      { type: '填空题', content: '三角形的内角和是（  ）度。', answer: '180', difficulty: 1 },
      { type: '填空题', content: '按角分类，三角形可以分为（  ）三角形、（  ）三角形和（  ）三角形。', answer: '锐角；直角；钝角', difficulty: 1 },
      { type: '填空题', content: '等腰三角形的两条（  ）相等，两个（  ）相等。', answer: '腰；底角', difficulty: 1 },
      { type: '填空题', content: '三角形中任意两边之和（  ）第三边。', answer: '大于', difficulty: 2 },
      { type: '判断题', content: '一个三角形中最多有一个直角。（  ）', answer: '√', difficulty: 2 },
      { type: '判断题', content: '等边三角形一定是锐角三角形。（  ）', answer: '√', difficulty: 2 },
      { type: '判断题', content: '一个三角形中可以有两个钝角。（  ）', answer: '×', difficulty: 1 },
      { type: '选择题', content: '一个三角形中，两个内角分别是50度和70度，第三个内角是（  ）度。\nA. 50  B. 60  C. 70', answer: 'B', difficulty: 2 },
      { type: '选择题', content: '下面哪组线段可以围成三角形？（  ）\nA. 3cm、4cm、8cm  B. 2cm、3cm、6cm  C. 3cm、4cm、5cm', answer: 'C', difficulty: 2 },
      { type: '计算题', content: '一个等腰三角形的一个底角是70度，它的顶角是多少度？', answer: '180-70×2=40（度）', difficulty: 2 },
      { type: '应用题', content: '一个三角形的三个内角的度数比是1:2:3，这个三角形中最大的角是多少度？是什么三角形？', answer: '180÷(1+2+3)×3=90（度），直角三角形', difficulty: 3 },
    ],
  },
  {
    id: 'g4x-u5',
    unitName: '小数的加法和减法',
    grade: 4,
    semester: '下',
    questions: [
      { type: '计算题', content: '3.5 + 2.8 =', answer: '6.3', difficulty: 1 },
      { type: '计算题', content: '7.2 - 3.5 =', answer: '3.7', difficulty: 1 },
      { type: '计算题', content: '10 - 4.36 =', answer: '5.64', difficulty: 2 },
      { type: '计算题', content: '12.5 + 7.86 =', answer: '20.36', difficulty: 2 },
      { type: '计算题', content: '8.45 - 3.67 =', answer: '4.78', difficulty: 2 },
      { type: '计算题', content: '15.3 + 4.7 - 6.8 =', answer: '13.2', difficulty: 2 },
      { type: '计算题', content: '20 - (5.4 + 3.6) =', answer: '11', difficulty: 2 },
      { type: '计算题', content: '6.38 + 2.45 + 3.62 =', answer: '12.45', difficulty: 2 },
      { type: '计算题', content: '9.56 - 2.78 - 4.22 =', answer: '2.56', difficulty: 2 },
      { type: '选择题', content: '5.2 + 3.8 - 5.2 + 3.8 =（  ）\nA. 0  B. 7.6  C. 15.2', answer: 'B', difficulty: 3 },
      { type: '应用题', content: '小明买一本书花了12.5元，买一支钢笔花了8.6元，他付了25元，应找回多少元？', answer: '25-12.5-8.6=3.9（元）', difficulty: 2 },
      { type: '应用题', content: '一根绳子长10米，第一次剪去3.5米，第二次剪去2.8米，还剩多少米？', answer: '10-3.5-2.8=3.7（米）', difficulty: 2 },
    ],
  },

  // ==================== 五年级上册 ====================
  {
    id: 'g5s-u1',
    unitName: '小数乘法',
    grade: 5,
    semester: '上',
    questions: [
      { type: '计算题', content: '2.5 × 3 =', answer: '7.5', difficulty: 1 },
      { type: '计算题', content: '0.8 × 0.5 =', answer: '0.4', difficulty: 1 },
      { type: '计算题', content: '3.6 × 0.25 =', answer: '0.9', difficulty: 2 },
      { type: '计算题', content: '1.25 × 0.8 =', answer: '1', difficulty: 1 },
      { type: '计算题', content: '4.5 × 12 =', answer: '54', difficulty: 1 },
      { type: '计算题', content: '0.35 × 0.4 =', answer: '0.14', difficulty: 2 },
      { type: '计算题', content: '2.4 × 0.15 =', answer: '0.36', difficulty: 2 },
      { type: '计算题', content: '7.2 × 0.5 =', answer: '3.6', difficulty: 1 },
      { type: '估算题', content: '估算：2.9 × 3.1 ≈（  ）', answer: '9', difficulty: 2 },
      { type: '应用题', content: '苹果每千克5.6元，买3.5千克需要多少元？', answer: '5.6×3.5=19.6（元）', difficulty: 2 },
      { type: '应用题', content: '一块长方形菜地，长8.5米，宽4.6米，这块菜地的面积是多少平方米？', answer: '8.5×4.6=39.1（平方米）', difficulty: 2 },
      { type: '应用题', content: '小明家每月用水8.5吨，每吨水费2.4元，小明家每月要交水费多少元？', answer: '8.5×2.4=20.4（元）', difficulty: 2 },
    ],
  },
  {
    id: 'g5s-u2',
    unitName: '小数除法',
    grade: 5,
    semester: '上',
    questions: [
      { type: '计算题', content: '7.2 ÷ 0.8 =', answer: '9', difficulty: 1 },
      { type: '计算题', content: '4.5 ÷ 0.05 =', answer: '90', difficulty: 1 },
      { type: '计算题', content: '6.3 ÷ 0.7 =', answer: '9', difficulty: 1 },
      { type: '计算题', content: '12.6 ÷ 0.3 =', answer: '42', difficulty: 1 },
      { type: '计算题', content: '5.6 ÷ 0.04 =', answer: '140', difficulty: 2 },
      { type: '计算题', content: '3.6 ÷ 1.2 =', answer: '3', difficulty: 1 },
      { type: '计算题', content: '10 ÷ 0.25 =', answer: '40', difficulty: 1 },
      { type: '计算题', content: '7.5 ÷ 2.5 =', answer: '3', difficulty: 1 },
      { type: '填空题', content: '5.7454545...是一个（  ）小数，用简便方法写作（  ）。', answer: '循环；5.74̇5̇', difficulty: 2 },
      { type: '选择题', content: '下面各数中，是有限小数的是（  ）。\nA. 1/3  B. 2/5  C. 5/6', answer: 'B', difficulty: 2 },
      { type: '应用题', content: '妈妈买了4.5千克苹果，花了27元，平均每千克苹果多少元？', answer: '27÷4.5=6（元）', difficulty: 2 },
      { type: '应用题', content: '一辆汽车行驶15.6千米用了1.2升汽油，平均每升汽油能行驶多少千米？', answer: '15.6÷1.2=13（千米）', difficulty: 2 },
    ],
  },
  {
    id: 'g5s-u3',
    unitName: '简易方程',
    grade: 5,
    semester: '上',
    questions: [
      { type: '填空题', content: '用字母表示乘法分配律：（a + b）× c =（  ）', answer: 'a×c + b×c', difficulty: 1 },
      { type: '填空题', content: '用字母表示长方形的周长公式：C =（  ）', answer: '2(a + b)', difficulty: 1 },
      { type: '填空题', content: '用字母表示正方形的面积公式：S =（  ）', answer: 'a²', difficulty: 1 },
      { type: '填空题', content: '当 a = 5 时，2a + 3 =（  ）。', answer: '13', difficulty: 2 },
      { type: '填空题', content: '当 x = 4 时，x² - 2x =（  ）。', answer: '8', difficulty: 2 },
      { type: '计算题', content: '解方程：\nx + 8 = 15', answer: 'x = 7', difficulty: 1 },
      { type: '计算题', content: '解方程：\nx - 3.5 = 7.2', answer: 'x = 10.7', difficulty: 1 },
      { type: '计算题', content: '解方程：\n2x = 18', answer: 'x = 9', difficulty: 1 },
      { type: '计算题', content: '解方程：\n3x + 5 = 20', answer: 'x = 5', difficulty: 2 },
      { type: '计算题', content: '解方程：\n4x - 7 = 13', answer: 'x = 5', difficulty: 2 },
      { type: '应用题', content: '小明买了3本笔记本，每本x元，付了20元，找回5元。列出方程并求解。', answer: '3x + 5 = 20，x = 5', difficulty: 3 },
      { type: '应用题', content: '一个数的3倍减去4.5等于10.5，这个数是多少？（用方程解）', answer: '3x - 4.5 = 10.5，x = 5', difficulty: 3 },
    ],
  },
  {
    id: 'g5s-u4',
    unitName: '多边形的面积',
    grade: 5,
    semester: '上',
    questions: [
      { type: '填空题', content: '平行四边形的面积 =（  ）×（  ）', answer: '底；高', difficulty: 1 },
      { type: '填空题', content: '三角形的面积 =（  ）×（  ）÷ 2', answer: '底；高', difficulty: 1 },
      { type: '填空题', content: '梯形的面积 =（  ）×（  ）÷ 2', answer: '(上底+下底)；高', difficulty: 1 },
      { type: '计算题', content: '一个平行四边形，底12厘米，高8厘米，面积是多少？', answer: '12×8=96（平方厘米）', difficulty: 1 },
      { type: '计算题', content: '一个三角形，底10分米，高6分米，面积是多少？', answer: '10×6÷2=30（平方分米）', difficulty: 1 },
      { type: '计算题', content: '一个梯形，上底5厘米，下底9厘米，高6厘米，面积是多少？', answer: '(5+9)×6÷2=42（平方厘米）', difficulty: 2 },
      { type: '计算题', content: '一个平行四边形的面积是48平方米，底是8米，高是多少？', answer: '48÷8=6（米）', difficulty: 2 },
      { type: '计算题', content: '一个三角形的面积是25平方厘米，底是10厘米，高是多少？', answer: '25×2÷10=5（厘米）', difficulty: 2 },
      { type: '选择题', content: '一个平行四边形和一个三角形等底等高，平行四边形的面积是三角形的（  ）倍。\nA. 2  B. 3  C. 4', answer: 'A', difficulty: 2 },
      { type: '判断题', content: '两个面积相等的三角形一定能拼成一个平行四边形。（  ）', answer: '×', difficulty: 3 },
      { type: '应用题', content: '一块平行四边形菜地，底15米，高8米，如果每平方米收白菜6千克，这块地一共可以收白菜多少千克？', answer: '15×8×6=720（千克）', difficulty: 2 },
      { type: '应用题', content: '一块梯形花坛，上底4米，下底6米，高5米，面积是多少平方米？', answer: '(4+6)×5÷2=25（平方米）', difficulty: 2 },
    ],
  },

  // ==================== 五年级下册 ====================
  {
    id: 'g5x-u1',
    unitName: '观察物体',
    grade: 5,
    semester: '下',
    questions: [
      { type: '判断题', content: '从不同方向观察同一个物体，看到的形状可能不同。（  ）', answer: '√', difficulty: 1 },
      { type: '判断题', content: '从正面看到的形状是正方形，这个物体一定是正方体。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '一个物体从左面和右面看到的形状一定相同。（  ）', answer: '×', difficulty: 2 },
      { type: '选择题', content: '一个正方体从正面、上面和左面看到的都是（  ）。\nA. 三角形  B. 正方形  C. 长方形', answer: 'B', difficulty: 1 },
      { type: '选择题', content: '用4个小正方体搭成一个立体图形，从正面看到的是3个正方形，从上面看到的是2个正方形，这个立体图形最少需要（  ）个小正方体。\nA. 3  B. 4  C. 5', answer: 'B', difficulty: 3 },
      { type: '判断题', content: '一个长方体从不同方向看到的形状一定都是长方形。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '观察一个物体，最多能同时看到3个面。（  ）', answer: '√', difficulty: 1 },
      { type: '选择题', content: '一个圆柱从正面看到的是一个（  ）。\nA. 圆  B. 长方形  C. 三角形', answer: 'B', difficulty: 1 },
      { type: '判断题', content: '用同样的小正方体搭成的立体图形，从正面看到的形状相同，它们的实际形状也一定相同。（  ）', answer: '×', difficulty: 3 },
      { type: '选择题', content: '从上面看一个立体图形，看到的是"田"字形，这个立体图形至少由（  ）个小正方体组成。\nA. 4  B. 5  C. 6', answer: 'A', difficulty: 3 },
    ],
  },
  {
    id: 'g5x-u2',
    unitName: '因数与倍数',
    grade: 5,
    semester: '下',
    questions: [
      { type: '填空题', content: '在算式 3 × 7 = 21 中，（  ）和（  ）是21的因数，21是（  ）和（  ）的倍数。', answer: '3；7；3；7', difficulty: 1 },
      { type: '填空题', content: '一个数的最小因数是（  ），最大因数是（  ）。', answer: '1；它本身', difficulty: 1 },
      { type: '填空题', content: '一个数的最小倍数是（  ），（  ）最大倍数。', answer: '它本身；没有', difficulty: 1 },
      { type: '填空题', content: '在1~20中，既是偶数又是质数的数是（  ）。', answer: '2', difficulty: 2 },
      { type: '填空题', content: '12的因数有（  ），其中质数有（  ）。', answer: '1、2、3、4、6、12；2、3', difficulty: 2 },
      { type: '判断题', content: '1是所有非零自然数的因数。（  ）', answer: '√', difficulty: 1 },
      { type: '判断题', content: '一个数的因数的个数是有限的。（  ）', answer: '√', difficulty: 1 },
      { type: '判断题', content: '所有的质数都是奇数。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '两个质数的和一定是偶数。（  ）', answer: '×', difficulty: 3 },
      { type: '选择题', content: '下面各数中，既是奇数又是合数的是（  ）。\nA. 7  B. 9  C. 2', answer: 'B', difficulty: 2 },
      { type: '选择题', content: '下面各数中，是质数的是（  ）。\nA. 21  B. 29  C. 33', answer: 'B', difficulty: 2 },
      { type: '填空题', content: '50以内最大的质数是（  ）。', answer: '47', difficulty: 2 },
    ],
  },
  {
    id: 'g5x-u3',
    unitName: '长方体和正方体',
    grade: 5,
    semester: '下',
    questions: [
      { type: '填空题', content: '长方体有（  ）个面，（  ）条棱，（  ）个顶点。', answer: '6；12；8', difficulty: 1 },
      { type: '填空题', content: '长方体的表面积 =（  ）', answer: '(长×宽+长×高+宽×高)×2', difficulty: 1 },
      { type: '填空题', content: '长方体的体积 =（  ）', answer: '长×宽×高', difficulty: 1 },
      { type: '填空题', content: '正方体的体积 =（  ）', answer: '棱长×棱长×棱长', difficulty: 1 },
      { type: '填空题', content: '1立方米 =（  ）立方分米', answer: '1000', difficulty: 1 },
      { type: '计算题', content: '一个长方体，长8厘米，宽5厘米，高4厘米，表面积是多少？', answer: '(8×5+8×4+5×4)×2=184（平方厘米）', difficulty: 2 },
      { type: '计算题', content: '一个正方体，棱长6分米，体积是多少？', answer: '6×6×6=216（立方分米）', difficulty: 1 },
      { type: '计算题', content: '一个长方体，长10厘米，宽6厘米，高5厘米，体积是多少？', answer: '10×6×5=300（立方厘米）', difficulty: 1 },
      { type: '计算题', content: '一个正方体水箱，棱长4分米，它的容积是多少升？', answer: '4×4×4=64（升）', difficulty: 2 },
      { type: '应用题', content: '一个长方体游泳池，长50米，宽25米，深2米，这个游泳池的容积是多少立方米？', answer: '50×25×2=2500（立方米）', difficulty: 2 },
      { type: '应用题', content: '一个长方体纸箱，长40厘米，宽30厘米，高20厘米，做这个纸箱至少需要多少平方厘米的纸板？', answer: '(40×30+40×20+30×20)×2=5200（平方厘米）', difficulty: 2 },
      { type: '应用题', content: '一个正方体石块，棱长5分米，它的体积是多少立方分米？如果每立方分米重2.5千克，这块石块重多少千克？', answer: '5×5×5=125（立方分米），125×2.5=312.5（千克）', difficulty: 3 },
    ],
  },
  {
    id: 'g5x-u4',
    unitName: '分数的意义和性质',
    grade: 5,
    semester: '下',
    questions: [
      { type: '填空题', content: '把单位"1"平均分成8份，表示其中的3份，用分数表示是（  ），它的分数单位是（  ）。', answer: '3/8；1/8', difficulty: 1 },
      { type: '填空题', content: '3/4的分数单位是（  ），它有（  ）个这样的分数单位。', answer: '1/4；3', difficulty: 1 },
      { type: '填空题', content: '分子和分母（  ）的分数，叫做最简分数。', answer: '只有公因数1', difficulty: 1 },
      { type: '填空题', content: '把12/18化成最简分数是（  ）。', answer: '2/3', difficulty: 2 },
      { type: '填空题', content: '分数的分子和分母同时乘以或除以（  ）的数（0除外），分数的大小不变。', answer: '相同', difficulty: 1 },
      { type: '判断题', content: '分数的分子和分母同时加上同一个数，分数的大小不变。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '最简分数的分子和分母只有公因数1。（  ）', answer: '√', difficulty: 1 },
      { type: '判断题', content: '假分数都大于1。（  ）', answer: '×', difficulty: 2 },
      { type: '选择题', content: '下面各分数中，是最简分数的是（  ）。\nA. 4/8  B. 5/7  C. 6/9', answer: 'B', difficulty: 1 },
      { type: '选择题', content: '把5/6和3/4通分，用（  ）作公分母。\nA. 10  B. 12  C. 24', answer: 'B', difficulty: 2 },
      { type: '计算题', content: '把2/3和4/5通分。', answer: '2/3=10/15，4/5=12/15', difficulty: 2 },
      { type: '计算题', content: '把8/12化成最简分数。', answer: '8/12=2/3', difficulty: 2 },
    ],
  },
  {
    id: 'g5x-u5',
    unitName: '分数的加法和减法',
    grade: 5,
    semester: '下',
    questions: [
      { type: '计算题', content: '1/4 + 2/4 =', answer: '3/4', difficulty: 1 },
      { type: '计算题', content: '5/6 - 1/6 =', answer: '2/3', difficulty: 1 },
      { type: '计算题', content: '1/2 + 1/3 =', answer: '5/6', difficulty: 2 },
      { type: '计算题', content: '3/4 - 1/3 =', answer: '5/12', difficulty: 2 },
      { type: '计算题', content: '2/5 + 3/10 =', answer: '7/10', difficulty: 2 },
      { type: '计算题', content: '7/8 - 3/4 =', answer: '1/8', difficulty: 2 },
      { type: '计算题', content: '1 - 3/7 =', answer: '4/7', difficulty: 1 },
      { type: '计算题', content: '5/6 + 3/8 =', answer: '29/24', difficulty: 2 },
      { type: '计算题', content: '1/2 + 1/3 + 1/6 =', answer: '1', difficulty: 2 },
      { type: '计算题', content: '5/6 - 1/4 - 1/3 =', answer: '1/4', difficulty: 3 },
      { type: '应用题', content: '一根铁丝长2米，第一次用去1/3米，第二次用去1/4米，还剩多少米？', answer: '2 - 1/3 - 1/4 = 5/12（米）', difficulty: 2 },
      { type: '应用题', content: '一块蛋糕，小明吃了1/4，小红吃了1/3，两人一共吃了这块蛋糕的几分之几？', answer: '1/4 + 1/3 = 7/12', difficulty: 2 },
    ],
  },

  // ==================== 六年级上册 ====================
  {
    id: 'g6s-u1',
    unitName: '分数乘法',
    grade: 6,
    semester: '上',
    questions: [
      { type: '计算题', content: '2/3 × 3/4 =', answer: '1/2', difficulty: 1 },
      { type: '计算题', content: '5/6 × 12 =', answer: '10', difficulty: 1 },
      { type: '计算题', content: '3/8 × 4/9 =', answer: '1/6', difficulty: 2 },
      { type: '计算题', content: '7/12 × 6/7 =', answer: '1/2', difficulty: 1 },
      { type: '计算题', content: '15 × 2/5 =', answer: '6', difficulty: 1 },
      { type: '计算题', content: '4/5 × 5/8 =', answer: '1/2', difficulty: 1 },
      { type: '计算题', content: '2/3 × 3/5 × 5/7 =', answer: '2/7', difficulty: 2 },
      { type: '计算题', content: '3/4 × 8 =', answer: '6', difficulty: 1 },
      { type: '应用题', content: '一根绳子长12米，用去了它的2/3，用去了多少米？', answer: '12×2/3=8（米）', difficulty: 2 },
      { type: '应用题', content: '一本书有240页，小红第一天看了全书的1/4，第二天看了全书的1/6，两天一共看了多少页？', answer: '240×1/4+240×1/6=100（页）', difficulty: 2 },
      { type: '应用题', content: '果园里有苹果树120棵，梨树的棵数是苹果树的3/4，梨树有多少棵？', answer: '120×3/4=90（棵）', difficulty: 2 },
      { type: '应用题', content: '一件衣服原价200元，现在打八折出售，现在售价多少元？', answer: '200×8/10=160（元）', difficulty: 3 },
    ],
  },
  {
    id: 'g6s-u2',
    unitName: '位置与方向（二）',
    grade: 6,
    semester: '上',
    questions: [
      { type: '填空题', content: '确定物体位置的两个条件是（  ）和（  ）。', answer: '方向；距离', difficulty: 1 },
      { type: '填空题', content: '小明在小红的北偏东30度方向200米处，那么小红在小明的（  ）方向（  ）米处。', answer: '南偏西30度；200', difficulty: 2 },
      { type: '填空题', content: '以学校为观测点，图书馆在学校的北偏西45度方向300米处，这句话中的观测点是（  ）。', answer: '学校', difficulty: 1 },
      { type: '填空题', content: '描述路线时，需要说清楚每一段的（  ）和（  ）。', answer: '方向；距离', difficulty: 1 },
      { type: '填空题', content: '东偏北30度也可以说成（  ）偏（  ）60度。', answer: '北；东', difficulty: 2 },
      { type: '选择题', content: '以广场为观测点，学校在广场的北偏西35度方向，那么以学校为观测点，广场在学校的（  ）方向。\nA. 南偏东35度  B. 南偏西35度  C. 北偏东35度', answer: 'A', difficulty: 2 },
      { type: '判断题', content: '确定位置时，方向和距离缺一不可。（  ）', answer: '√', difficulty: 1 },
      { type: '判断题', content: '北偏东40度和东偏北50度表示的方向相同。（  ）', answer: '√', difficulty: 2 },
      { type: '应用题', content: '从学校出发，向北偏东30度方向走400米到书店，再向东偏南45度方向走300米到超市。请描述从超市回到学校的路线。', answer: '从超市出发，向西偏北45度方向走300米到书店，再向南偏西30度方向走400米到学校', difficulty: 3 },
      { type: '填空题', content: '在平面图上，通常用（  ）方向为基准方向来描述物体的位置。', answer: '北', difficulty: 1 },
    ],
  },
  {
    id: 'g6s-u3',
    unitName: '分数除法',
    grade: 6,
    semester: '上',
    questions: [
      { type: '计算题', content: '3/4 ÷ 3 =', answer: '1/4', difficulty: 1 },
      { type: '计算题', content: '5/6 ÷ 5/12 =', answer: '2', difficulty: 1 },
      { type: '计算题', content: '8 ÷ 4/5 =', answer: '10', difficulty: 1 },
      { type: '计算题', content: '2/3 ÷ 4/9 =', answer: '3/2', difficulty: 2 },
      { type: '计算题', content: '7/8 ÷ 7 =', answer: '1/8', difficulty: 1 },
      { type: '计算题', content: '12 ÷ 3/4 =', answer: '16', difficulty: 1 },
      { type: '计算题', content: '5/6 ÷ 10/9 =', answer: '3/4', difficulty: 2 },
      { type: '计算题', content: '4/5 ÷ 2/3 =', answer: '6/5', difficulty: 2 },
      { type: '应用题', content: '一桶油重20千克，用去了它的3/4，用去了多少千克？', answer: '20×3/4=15（千克）', difficulty: 2 },
      { type: '应用题', content: '小明看一本书，已经看了全书的2/5，正好是60页，这本书一共有多少页？', answer: '60÷2/5=150（页）', difficulty: 2 },
      { type: '应用题', content: '一段路程，甲车行了全程的3/8，正好是45千米，全程是多少千米？', answer: '45÷3/8=120（千米）', difficulty: 2 },
      { type: '应用题', content: '学校图书馆有故事书480本，是科技书的3/5，科技书有多少本？', answer: '480÷3/5=800（本）', difficulty: 3 },
    ],
  },
  {
    id: 'g6s-u4',
    unitName: '比',
    grade: 6,
    semester: '上',
    questions: [
      { type: '填空题', content: '两个数（  ）又叫做两个数的比。', answer: '相除', difficulty: 1 },
      { type: '填空题', content: '15 ÷ 10 =（  ）：（  ） =（  ）/（  ）', answer: '15；10；15；10', difficulty: 1 },
      { type: '填空题', content: '比的前项和后项同时乘以或除以（  ）的数（0除外），比值不变。', answer: '相同', difficulty: 1 },
      { type: '填空题', content: '化简比：12:8 =（  ）：（  ）', answer: '3；2', difficulty: 1 },
      { type: '填空题', content: '化简比：0.5:0.3 =（  ）：（  ）', answer: '5；3', difficulty: 2 },
      { type: '填空题', content: '化简比：2/3:4/9 =（  ）：（  ）', answer: '3；2', difficulty: 2 },
      { type: '计算题', content: '求比值：24:16 =', answer: '3/2（或1.5）', difficulty: 1 },
      { type: '计算题', content: '求比值：3/5:2/5 =', answer: '3/2（或1.5）', difficulty: 1 },
      { type: '选择题', content: '比的前项是6，比值是2/3，比的后项是（  ）。\nA. 4  B. 9  C. 12', answer: 'B', difficulty: 2 },
      { type: '判断题', content: '比的前项不能为0。（  ）', answer: '√', difficulty: 1 },
      { type: '应用题', content: '一杯糖水中，糖和水的比是1:20，如果有5克糖，需要加水多少克？', answer: '5×20=100（克）', difficulty: 2 },
      { type: '应用题', content: '甲乙两数的比是3:5，甲数是27，乙数是多少？', answer: '27÷3×5=45', difficulty: 2 },
    ],
  },
  {
    id: 'g6s-u5',
    unitName: '圆',
    grade: 6,
    semester: '上',
    questions: [
      { type: '填空题', content: '圆的周长 C =（  ）或 C =（  ）', answer: 'πd；2πr', difficulty: 1 },
      { type: '填空题', content: '圆的面积 S =（  ）', answer: 'πr²', difficulty: 1 },
      { type: '填空题', content: '一个圆的半径是3厘米，它的直径是（  ）厘米，周长是（  ）厘米。', answer: '6；18.84', difficulty: 2 },
      { type: '填空题', content: '一个圆的直径是10厘米，它的面积是（  ）平方厘米。（π取3.14）', answer: '78.5', difficulty: 2 },
      { type: '计算题', content: '一个圆的半径是5厘米，求它的周长。（π取3.14）', answer: '2×3.14×5=31.4（厘米）', difficulty: 1 },
      { type: '计算题', content: '一个圆的直径是8分米，求它的面积。（π取3.14）', answer: '3.14×(8÷2)²=50.24（平方分米）', difficulty: 2 },
      { type: '计算题', content: '一个半圆形花坛，直径是6米，这个花坛的周长是多少米？（π取3.14）', answer: '3.14×6÷2+6=15.42（米）', difficulty: 3 },
      { type: '选择题', content: '圆的半径扩大2倍，面积扩大（  ）倍。\nA. 2  B. 4  C. 8', answer: 'B', difficulty: 2 },
      { type: '判断题', content: '所有的直径都是半径的2倍。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '圆是轴对称图形，它有无数条对称轴。（  ）', answer: '√', difficulty: 1 },
      { type: '应用题', content: '一个圆形水池，周长是31.4米，它的面积是多少平方米？（π取3.14）', answer: '31.4÷3.14÷2=5（米），3.14×5²=78.5（平方米）', difficulty: 3 },
      { type: '应用题', content: '一个圆形花坛的直径是10米，在花坛周围铺一条2米宽的小路，小路的面积是多少平方米？（π取3.14）', answer: '3.14×(5+2)²-3.14×5²=3.14×(49-25)=75.36（平方米）', difficulty: 3 },
    ],
  },

  // ==================== 六年级下册 ====================
  {
    id: 'g6x-u1',
    unitName: '负数',
    grade: 6,
    semester: '下',
    questions: [
      { type: '填空题', content: '在数轴上，0右边的数是（  ）数，左边的数是（  ）数。', answer: '正；负', difficulty: 1 },
      { type: '填空题', content: '如果零上5度记作+5度，那么零下3度记作（  ）度。', answer: '-3', difficulty: 1 },
      { type: '填空题', content: '如果收入500元记作+500元，那么支出300元记作（  ）元。', answer: '-300', difficulty: 1 },
      { type: '填空题', content: '在-3、0、+5、-1.5、+2.4中，正数有（  ），负数有（  ）。', answer: '+5、+2.4；-3、-1.5', difficulty: 1 },
      { type: '填空题', content: '（  ）既不是正数，也不是负数。', answer: '0', difficulty: 1 },
      { type: '判断题', content: '0是正数。（  ）', answer: '×', difficulty: 1 },
      { type: '判断题', content: '-5大于-3。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '所有的正数都大于负数。（  ）', answer: '√', difficulty: 1 },
      { type: '判断题', content: '在数轴上，从左到右的顺序就是数从小到大的顺序。（  ）', answer: '√', difficulty: 1 },
      { type: '选择题', content: '下面各数中，最小的数是（  ）。\nA. -2  B. 0  C. 1', answer: 'A', difficulty: 1 },
      { type: '选择题', content: '海拔-100米表示（  ）。\nA. 高于海平面100米  B. 低于海平面100米  C. 海平面100米处', answer: 'B', difficulty: 1 },
      { type: '填空题', content: '把+3、-5、0、-1、+2按从小到大的顺序排列：（  ）<（  ）<（  ）<（  ）<（  ）', answer: '-5 < -1 < 0 < +2 < +3', difficulty: 2 },
    ],
  },
  {
    id: 'g6x-u2',
    unitName: '百分数',
    grade: 6,
    semester: '下',
    questions: [
      { type: '填空题', content: '3/5 =（  ）/20 =（  ）% =（  ）（填小数）', answer: '12；60；0.6', difficulty: 1 },
      { type: '填空题', content: '45%读作（  ），百分之三十五写作（  ）。', answer: '百分之四十五；35%', difficulty: 1 },
      { type: '填空题', content: '一件商品打八折出售，表示现价是原价的（  ）%。', answer: '80', difficulty: 1 },
      { type: '填空题', content: '出勤率 =（  ）÷（  ）× 100%', answer: '出勤人数；总人数', difficulty: 1 },
      { type: '计算题', content: '把3/8化成百分数。', answer: '37.5%', difficulty: 2 },
      { type: '计算题', content: '把75%化成分数。', answer: '3/4', difficulty: 1 },
      { type: '计算题', content: '250的40%是多少？', answer: '100', difficulty: 1 },
      { type: '计算题', content: '一个数的25%是60，这个数是多少？', answer: '240', difficulty: 2 },
      { type: '选择题', content: '某班有50人，今天有2人请假，今天的出勤率是（  ）。\nA. 96%  B. 4%  C. 98%', answer: 'A', difficulty: 2 },
      { type: '判断题', content: '百分数的分子一定小于100。（  ）', answer: '×', difficulty: 1 },
      { type: '应用题', content: '一件衣服原价300元，现在打七五折出售，现在售价多少元？', answer: '300×75%=225（元）', difficulty: 2 },
      { type: '应用题', content: '小明存入银行5000元，年利率是2.5%，存2年，到期后利息是多少元？', answer: '5000×2.5%×2=250（元）', difficulty: 3 },
    ],
  },
  {
    id: 'g6x-u3',
    unitName: '圆柱与圆锥',
    grade: 6,
    semester: '下',
    questions: [
      { type: '填空题', content: '圆柱的侧面积 =（  ）×（  ）', answer: '底面周长；高', difficulty: 1 },
      { type: '填空题', content: '圆柱的体积 =（  ）', answer: '底面积×高', difficulty: 1 },
      { type: '填空题', content: '圆锥的体积 =（  ）', answer: '1/3×底面积×高', difficulty: 1 },
      { type: '填空题', content: '一个圆柱和一个圆锥等底等高，圆柱的体积是圆锥体积的（  ）倍。', answer: '3', difficulty: 1 },
      { type: '计算题', content: '一个圆柱，底面半径是3厘米，高是10厘米，体积是多少？（π取3.14）', answer: '3.14×3²×10=282.6（立方厘米）', difficulty: 2 },
      { type: '计算题', content: '一个圆锥，底面直径是6米，高是4米，体积是多少？（π取3.14）', answer: '1/3×3.14×(6÷2)²×4=37.68（立方米）', difficulty: 2 },
      { type: '计算题', content: '一个圆柱的底面周长是12.56厘米，高是5厘米，侧面积是多少？', answer: '12.56×5=62.8（平方厘米）', difficulty: 1 },
      { type: '计算题', content: '一个圆柱的底面半径是2分米，高是8分米，表面积是多少？（π取3.14）', answer: '2×3.14×2×8+3.14×2²=125.6（平方分米）', difficulty: 3 },
      { type: '选择题', content: '把一个圆柱的侧面展开，得到一个（  ）。\nA. 长方形  B. 正方形  C. 长方形或正方形', answer: 'C', difficulty: 2 },
      { type: '判断题', content: '圆锥的体积是圆柱体积的1/3。（  ）', answer: '×', difficulty: 2 },
      { type: '应用题', content: '一个圆柱形水桶，底面半径是20厘米，高是50厘米，这个水桶的容积是多少升？（π取3.14）', answer: '3.14×20²×50=62800（立方厘米）=62.8（升）', difficulty: 2 },
      { type: '应用题', content: '一个圆锥形沙堆，底面直径是4米，高是1.5米，这堆沙的体积是多少立方米？（π取3.14）', answer: '1/3×3.14×(4÷2)²×1.5=6.28（立方米）', difficulty: 2 },
    ],
  },
  {
    id: 'g6x-u4',
    unitName: '比例',
    grade: 6,
    semester: '下',
    questions: [
      { type: '填空题', content: '表示两个比相等的式子叫做（  ）。', answer: '比例', difficulty: 1 },
      { type: '填空题', content: '在比例中，两个外项的积（  ）两个内项的积。', answer: '等于', difficulty: 1 },
      { type: '填空题', content: '如果 a × 3 = b × 5，那么 a:b =（  ）：（  ）。', answer: '5；3', difficulty: 2 },
      { type: '填空题', content: '图上距离和实际距离的比，叫做这幅图的（  ）。', answer: '比例尺', difficulty: 1 },
      { type: '填空题', content: '一幅地图的比例尺是1:5000000，图上1厘米表示实际距离（  ）千米。', answer: '50', difficulty: 2 },
      { type: '计算题', content: '解比例：\n2:5 = x:15', answer: 'x = 6', difficulty: 1 },
      { type: '计算题', content: '解比例：\n3/x = 9/12', answer: 'x = 4', difficulty: 2 },
      { type: '计算题', content: '解比例：\nx/4 = 7/8', answer: 'x = 3.5', difficulty: 2 },
      { type: '判断题', content: '两个比可以组成一个比例。（  ）', answer: '×', difficulty: 2 },
      { type: '判断题', content: '如果3a=5b，那么a:b=5:3。（  ）', answer: '√', difficulty: 2 },
      { type: '应用题', content: '在一幅比例尺是1:2000000的地图上，量得甲乙两地的距离是5厘米，甲乙两地的实际距离是多少千米？', answer: '5×2000000=10000000（厘米）=100（千米）', difficulty: 2 },
      { type: '应用题', content: '一辆汽车3小时行驶了180千米，照这样的速度，5小时行驶多少千米？（用比例解）', answer: '180/3=x/5，x=300（千米）', difficulty: 3 },
    ],
  },
];

/**
 * 根据年级和学期获取可用单元列表
 */
export function getUnitsByGradeAndSemester(grade: number, semester: '上' | '下'): UnitQuestion[] {
  return unitTestData.filter(u => u.grade === grade && u.semester === semester);
}

/**
 * 获取所有年级学期组合
 */
export function getAllGradeSemesterCombinations(): { grade: number; semester: '上' | '下' }[] {
  const combos: { grade: number; semester: '上' | '下' }[] = [];
  for (let g = 1; g <= 6; g++) {
    combos.push({ grade: g, semester: '上' });
    combos.push({ grade: g, semester: '下' });
  }
  return combos;
}

/**
 * 从指定单元中随机抽取指定数量和难度的题目
 */
export function getRandomQuestions(
  unitIds: string[],
  count: number,
  difficulty?: 1 | 2 | 3,
): { type: string; content: string; answer: string; difficulty: 1 | 2 | 3; unitName: string }[] {
  // 收集所有符合条件的题目
  let pool: { type: string; content: string; answer: string; difficulty: 1 | 2 | 3; unitName: string }[] = [];

  for (const unitId of unitIds) {
    const unit = unitTestData.find(u => u.id === unitId);
    if (unit) {
      for (const q of unit.questions) {
        if (difficulty === undefined || q.difficulty === difficulty) {
          pool.push({ ...q, unitName: unit.unitName });
        }
      }
    }
  }

  // 如果指定难度后题目不足，则从所有难度中补充
  if (pool.length < count && difficulty !== undefined) {
    for (const unitId of unitIds) {
      const unit = unitTestData.find(u => u.id === unitId);
      if (unit) {
        for (const q of unit.questions) {
          if (q.difficulty !== difficulty && !pool.find(p => p.content === q.content)) {
            pool.push({ ...q, unitName: unit.unitName });
          }
        }
      }
    }
  }

  // 随机打乱
  pool.sort(() => Math.random() - 0.5);

  // 返回指定数量
  return pool.slice(0, count);
}
